### ISSUE TITLE
Comprehension with unpack

### ISSUE THREAD

**Issue by ALavallee** [FlyableDev/Flyable#38]
The compiler raise an exception when trying to handle comprehension with multiple for items. To fix this we need a unpack routine in the code. 

`old_price = {'milk': 1.02, 'coffee': 2.5, 'bread': 2.5}

dollar_to_pound = 0.76
new_price = {item: value * dollar_to_pound for (item, value) in old_price.items()}
print(new_price)`

**Comment by ALavallee** [comment]
Missing unpacking iterables

**Comment by ALavallee** [comment]
@YohanFinet Update on what is needed to have.

**Comment by YohanFinet** [comment]
Unpacking dict and iterables done here: 999c2a1824ca5616368f2f46c6ff6b83fadf3793

Remaining work to be done on unpacking described here: #101
