### ISSUE TITLE
Variable scope issue

### ISSUE THREAD

**Issue by YohanFinet** [FlyableDev/Flyable#39]
When a local variable has the same name as a global variable, flyable thinks we are talking about the global variable.

example 1:
```
x = "global "

def foo():
    x = x * 2
    print(x)

foo()
print(x)
```
cpython: error
flyable: prints global global

example 2:
```
x = "global "

def foo():
    x = "hello"
    print(x)

foo()
print(x)
```
cpython: prints hello global
flyable: prints hello hello

**Comment by YohanFinet** [comment]
There's an issue with the scope of nested functions that might be related.

example:

```
def outer():
    x = "hello"

    def inner():
        x = "world"
        print("inner:" + x)

    inner()
    print("outer:" + x)

def foo():
    inner()

outer()
foo()
```
the above code prints:
inner:world
outer:hello
inner:world

But it should raise an error since foo() shouldn't be able to call inner().

**Comment by ALavallee** [comment]
@MoSk3 Is this one good to close?

**Comment by MoSk3** [comment]
Not fully, still working on the error raising

**Comment by ALavallee** [comment]
Cpython opcodes take cares of that. We will just need to lookup provided in the Function Frame.
