### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by WhoAteDaCake** [FlyableDev/Flyable#46]
Hello, I've found this project on hackernews, was just wondering if it's something you're working on part-time or does it have any backing or roadmap etc.

Thanks :)

**Comment by ALavallee** [comment]
Hi ! Thank for you interess in the project =) !

It's something we work on part time right now (full-time between mandates) . We are currently looking for more funding to accelerate the project development. We do have an internal roadmap to ensure stability, perfomance and compatibility with Python.

If you would like to help in any way we are open to any type of contributions ! :)  If you have any questions don't hesitate.
