### ISSUE TITLE
[BUG] infinite recursion in load_lib_and_dependecies

### ISSUE THREAD

**Issue by WhoAteDaCake** [FlyableDev/Flyable#47]
`library_loader.load_lib_and_dependecies` will cause to go into a infinite recursion when ran on linux. Might want to limit how many nested calls can be made.

**Comment by ALavallee** [comment]
I'll take a look ASAP. I know that we had some issues with that. I do remember implementing something to make it work
We mainly dev / test on Windows for now so any helps on Linux is REALLY appreciated.
I'll let you know.

Thank you ! =)

**Comment by ALavallee** [comment]
Hi ,
Did you had time to test again with a different working directory :) ?
Let me know :) !

Thank you !

**Comment by WhoAteDaCake** [comment]
Hey, sorry for not responding, Github didn't show me a notification for your message. I'll try it now

**Comment by WhoAteDaCake** [comment]
How would you run it from `Flyable/flyable` directory? Python doesn't recognise it as a module for me

**Comment by ALavallee** [comment]
The running script should be Flyable\flyable\main.py indeed. Otherwise you will have that error indeed.
However the Working directory is just a folder and must be set into 'Flyable/flyable'.

Here is what my PyCharm config looks like:
![image](https://user-images.githubusercontent.com/8020656/139728375-e4748f79-e393-4eb0-a720-aeae05f6dc46.png)

There is two steps that need to be done for have it working on linux:
- I need to update the CodeGen layer binaries for Linux
- Need to find a fix for #10 

Let me know if the issue persist. I have to admit I haven't tested it on Debian.

**Comment by ALavallee** [comment]
> Could you guide through me the steps you followed to run the test?

I'll ask @YohanFinet to update the doc with a section to run the test I'll update it when it's ready :) ! 

Thank you !

**Comment by WhoAteDaCake** [comment]
My working directory is definately `Flyable/flyable`. After running `export PYTHONPATH=$PWD/..` to make sure module can be loaded. Now I'm getting:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import flyable.compiler as com
  File "/home/toshiba/open-source/Flyable/flyable/compiler.py", line 1, in <module>
    import flyable.parse.parser as par
  File "/home/toshiba/open-source/Flyable/flyable/parse/parser.py", line 4, in <module>
    from flyable.parse.parser_visitor import ParserVisitor
  File "/home/toshiba/open-source/Flyable/flyable/parse/parser_visitor.py", line 8, in <module>
    import flyable.data.lang_class as lang_class
  File "/home/toshiba/open-source/Flyable/flyable/data/lang_class.py", line 2, in <module>
    import flyable.data.lang_class_type as class_type
  File "/home/toshiba/open-source/Flyable/flyable/data/lang_class_type.py", line 1, in <module>
    import flyable.code_gen.ref_counter as ref_counter
  File "/home/toshiba/open-source/Flyable/flyable/code_gen/ref_counter.py", line 5, in <module>
    import flyable.code_gen.fly_obj as fly_obj
  File "/home/toshiba/open-source/Flyable/flyable/code_gen/fly_obj.py", line 1, in <module>
    import flyable.code_gen.runtime as runtime
  File "/home/toshiba/open-source/Flyable/flyable/code_gen/runtime.py", line 2, in <module>
    from flyable.code_gen.code_gen import CodeFunc
  File "/home/toshiba/open-source/Flyable/flyable/code_gen/code_gen.py", line 5, in <module>
    from flyable.code_gen.code_builder import CodeBuilder
  File "/home/toshiba/open-source/Flyable/flyable/code_gen/code_builder.py", line 1, in <module>
    import flyable.code_gen.code_gen as gen
AttributeError: module 'flyable.code_gen' has no attribute 'code_gen'
```

**Comment by ALavallee** [comment]
Seems like it's able to find code_gen.py when it's inside runtime.py but not when it's inside the code_builder.py. It's kinda weird. I'll try to think of why it might happen to you.

Thank you again ! =)

**Comment by ALavallee** [comment]
Hi @WhoAteDaCake ,

I gave a few thoughts about your issue. Do you think that the fact that you're doing export PYTHONPATH=$PWD/.. can create a module that is accessible through two differents path and so the Python interpreter believes that the code_gen module is two different modules depending on what module you're importing it from ?

**Comment by WhoAteDaCake** [comment]
I'm not quite sure either. The example in PyCharm that you've shared should do the same under: 

* Add content roots to `PYTHONPATH`
* Add source roots to `PYTHONPATH`

Considering that if I don't add the custom `PYTHONPATH` it won't even find the flyable module, I'm not sure what's the alternative here. 
Would it be possible to move the test file out of the `flyable` directory to see if that's causing the issue?

**Comment by ALavallee** [comment]
If it's causing an issue I totally could :) ! 

Can you try it on your side and tell me it changes anything ? You just have to change the path in the  main.py file.

**Comment by WhoAteDaCake** [comment]
I've moved both `main.py` and `test.py` outside the flyable directory and stopped getting import failures, however, the program crashed with:

```
Compiling....
python: /home/antoine/Desktop/Workspace/llvm/lib/IR/Type.cpp:406: void llvm::StructType::setBody(llvm::ArrayRef<llvm::Type*>, bool): Assertion `isOpaque() && "Struct body already set!"' failed.
Aborted (core dumped)
```

**Comment by ALavallee** [comment]
Oh woaw it does work then =) ! Do you think it's a modification that should be implemented into Flyable ?

Yes this issue is because I didn't update the CodeGen layer for Linux for a while. I'll need to do it so you can compile any code :/.

You can open a new issue for that or I'll can try to remember it and update you on this issue when it's done. There is also #10 to fix.

Thank you so much !

**Comment by WhoAteDaCake** [comment]
I'm not sure if this is the best way to do it TBH, I'm still quite new to python, I assume you'd have to look at the way some other python libraries have created `examples` folders. :)

**Comment by WhoAteDaCake** [comment]
I'll close it, since we know of a workaround .
