### ISSUE TITLE
Binary operations are not working

### ISSUE THREAD

**Issue by Ecoral360** [FlyableDev/Flyable#50]
When you compile your code, the compiler simply takes the argument on the left to resolve the binary operation, whatever it is.
Ex: 
```py
3 + 4 # yields 3 
```  
```py
8 % 2 # yields 8
```

**Comment by ALavallee** [comment]
You're right something broke. I'm fixing that ASAP.

Makes me think we really need to finish #44 to stop introducing silly bugs like that.

**Comment by ALavallee** [comment]
Fix in : https://github.com/FlyableDev/Flyable/commit/5e80b589ac749a8272b2c58a08d51889fdde8423

Sorry for that issue. Basically what was happening is that the type hint of constant value wasn't removed after an bin op.

**Comment by ALavallee** [comment]
Thank you so much for your participation in the Flyable project ! :D 👍
