### ISSUE TITLE
Error with the modulo operator  

### ISSUE THREAD

**Issue by Ecoral360** [FlyableDev/Flyable#51]
If you take the modulo of a variable while in a for loop (the variable must be the one used by the for loop (i in the example)), it yields a tuple where the first element is the floor division and the second element is the actual modulo
Ex:
```py
for i in range(100)
    print(i % 2) # yields (i // 2, i % 2)
```

**Comment by ALavallee** [comment]
Thank you so much for findings these bugs ! :D

I'll take a look at this right now !

**Comment by Ecoral360** [comment]
I'm trying to test the speed of the compiler against Cython by comparing their speed for finding prime numbers (that's how I ran into those bugs :D)

**Comment by ALavallee** [comment]
Love that =) ! <3 
Keep up the gopod work !

**Comment by ALavallee** [comment]
If you're doing benchmark I just want to note that the for each loop with integers optimization is not in yet. You're going to see a HUGE difference when it will be.

**Comment by Ecoral360** [comment]
Perfect! I'll keep that in mind!

**Comment by ALavallee** [comment]
Done in https://github.com/FlyableDev/Flyable/commit/4e83c8469c0d4f4495f8a8cd780341c5b4ecbdf1:

**Comment by ALavallee** [comment]
Should be good. Because of wrong ID it was actually calling the divmod binary func instead of the remainder one.
