### ISSUE TITLE
Centralise build files

### ISSUE THREAD

**Issue by ALavallee** [FlyableDev/Flyable#55]
Right now runtime object files, python static and dynamic libraries are all prsent  in the multiples build folders. Ideally they would all be at the same place to avoid repetition.

**Comment by LeandreArseneault** [comment]
@ALavallee could you give me a list of runtime object files, python static files and python status and dynamic librairies?

**Comment by ALavallee** [comment]
- libFlyableRuntime.a (object file, link time)
- python310.lib (object file, link time)
- python310.dll (dynamic library, execution time)

I think it's all !

**Comment by ALavallee** [comment]
There is also the CodeGen layer related DLL but they are fine where they are.
