### ISSUE TITLE
AugAssign cause a CodeGen crash

### ISSUE THREAD

**Issue by LeandreArseneault** [FlyableDev/Flyable#58]
Sample code:
def test_compiler_crash():
    a = 2
    a *= 2
    return a

**Comment by ALavallee** [comment]
Maybe there is a link-time issue ? Gonna take a lot.

**Comment by ALavallee** [comment]
It's actually an assert error on the CodeGen layer due to the fact that there is an AugAssign ! I'll change the title.

**Comment by ALavallee** [comment]
Fix in : 
https://github.com/FlyableDev/Flyable/commit/b8465eb49137da374a7912e24ce518bbb8671d7e

Still seems to be an issue with the ref count so not exactly solved.

**Comment by ALavallee** [comment]
Fix the ref count of aug assign in : https://github.com/FlyableDev/Flyable/commit/59bc7dfc71f3c1ea830becf47f041ad8c09ae803
