### ISSUE TITLE
[BUG] load_lib_and_dependecies should check the error before appending to the path

### ISSUE THREAD

**Issue by WhoAteDaCake** [FlyableDev/Flyable#60]
My machine does not have `GLIBC_2.29`, so it causes a crash during the library loading, however, that exception is not handled properly and another attempt is made to load the library, with a messed up path (since the function just appends first piece of the path from error message), which causes a recursive loop, which will eventually crash the program.
 
A naive solution to the problem I've came up with is:

```python
def load_lib_and_dependecies(path, lib):
    try:
        return ctypes.CDLL(path + lib)
    except OSError as excp:
        # Get the name of the library not found
        error_msg = excp.args[0]
        # Should crash for any errors that are not missing object file 
        # errors, since we can't handle them
        if not "cannot open shared" in error_msg:
            # https://stackoverflow.com/questions/24752395/python-raise-from-usage
            # Helps to avoid a massive error message due to recursive calls
            # within an try/except
            raise excp from None
        lib_load = error_msg.split(" ")[0]
        lib_load = lib_load[0:-1]
        # Now load it
        load_lib_and_dependecies(path,lib_load)
        return load_lib_and_dependecies(path,lib)
```

**Comment by ALavallee** [comment]
I see. Well in this case I think this change is a good idea. 

I can change it myself but you can create a pull request  to be included into the code contributors ! :D

Thank you !

**Comment by WhoAteDaCake** [comment]
It's alright, I can't run the program on machine because of old glibc, so I wouldn't be able to contribute much

**Comment by ALavallee** [comment]
Oh all right I'll do that.
Why would you need a recent glibc ? Does CPython relies on a more recent one ?

**Comment by WhoAteDaCake** [comment]
I think one of the shared object files that you've built relies on it, might be libpython, I'd need to check again. My version is 2.28, so I'm right behind :sweat_smile:

**Comment by ALavallee** [comment]
I didn't build the Python object file. They come with the CPython setup. The reason is that on Windows CPython can only be compiled with MSVC from what I remember.

So yeah not impossible that the object file might present some imcompatibilities with older glibc.
