### ISSUE TITLE
compiling Issue (shared object files)

### ISSUE THREAD

**Issue by Martin-Vinci** [FlyableDev/Flyable#64]
There seems to be an issue with "_**Flyable/flyable/dyn_lib/linux64/libLLVMCore.so.13git**_"
![Screenshot from 2021-12-21 11-38-45](https://user-images.githubusercontent.com/78528528/146898780-d555a546-4ce6-41b1-912a-1ddad1f30ca1.png)

**Comment by ALavallee** [comment]
Hi Martin !

Indeed the linux build isn't updated. It's related to this issue :
https://github.com/FlyableDev/Flyable/issues/10

We need to rebuild the LLVM library on Linux with the current version of the CodeGen layer. I'm not much on Linux lately  but I'll try to do it ASAP.
