### ISSUE TITLE
"is not", "in" and "not in" comparison operators are not supported

### ISSUE THREAD

**Issue by YohanFinet** [FlyableDev/Flyable#70]
Related ast nodes:
- ast.IsNot
- ast.In
- ast.NotIn

Also, the cond_op method in the op_call module processes the "is" operator in the same way as the "==" operator, but it should not.

Finally, there's a bug when comparing two lists.
e.g.
`
print([1, 2] == [1, 2])
`

**Comment by Ecoral360** [comment]
Be cause "In" is fixed but not the other ones, I will open another issue with the other ones and close this one, if that's ok with you
