### ISSUE TITLE
Fix Binary_Add for Python Strings

### ISSUE THREAD

**Issue by daytonjallen** [FlyableDev/Flyable#79]
We're currently including the addition of strings in our Number Protocol call `PyNumber_Add`, however Python has a separate way of adding strings.

From their handling of the `Binary_Add` bytecode:
```c
// code ...
if (PyUnicode_CheckExact(left) &&
         PyUnicode_CheckExact(right)) {
    sum = unicode_concatenate(tstate, left, right, f, next_instr);
    /* unicode_concatenate consumed the ref to left */
}
else {
    sum = PyNumber_Add(left, right);
    Py_DECREF(left);
}
// ... code
```

**Comment by ALavallee** [comment]
Make sure it works for add on all others objects.

we might change something CPython if string still doesn't after.

**Comment by ALavallee** [comment]
We're not going to take any actions on that one. Unclear why CPython does it that way. It's probably faster for a very string intensive program but still.
